name: Trigger Docs Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in docs repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: 111-vk/nios_docs

          event-type: trigger-from-chai
